In [3]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
# ゼロ行列　zerso((行数, 列数))
# 引数はタプル型
zeros2x3 = np.zeros((2,3))
zeros2x3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# イチ行列 ones((行数, 列数))
# 引数はタプル型
ones2x3 = np.ones((2, 3))
ones2x3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [137]:
# arange(終)はrange()をリストにするようなもの
# arange(始, 終, 間隔)
# 終わりの値は含まない
print(np.arange(10))

print(np.arange(10, 30, 5))
print(np.arange(0, 2, 0.3))

[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [11]:
# linspace()等間隔な数列を生成(始, 終, 個数)
# 終わりの値を含む等間隔の個数分の数値
# 画像処理や時系列データの線形補完
print(np.linspace(0, np.pi, 10))

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


In [28]:
# reshape(行数, 列数) 配列の形を変える
# np.は必要ない？

array = np.array([1, 2, 3, 4, 5, 6])

# reshape(行数, 列数)
# 配列を任意の行列に変形
# 要素の順番は変わらない点がtranspose()と異なる
arr2x3 = array.reshape(2, 3)
print(arr2x3)

# 割り切れない数値ではreshape不可
# 今回の場合はreshape(2, 4)など

[[1 2 3]
 [4 5 6]]


In [26]:
# ravel() 配列の形を変える
# np.は必要ない？
array = np.array([1, 2, 3, 4, 5, 6])
arr2x3 = array.reshape(2, 3)

# ravel()
# 行列を一次元にほどく、一次元配列に変形する
a = arr2x3.ravel()
print(a)

[1 2 3 4 5 6]


In [30]:
# transpose() 配列の形を変える
# np.は必要ない？
array = np.array([1, 2, 3, 4, 5, 6])
arr2x3 = array.reshape(2, 3)
    '''[[1 2 3]
         [4 5 6]]'''

# Tもしくはtranspose()
# 転置行列、行列の入れ替え
# 要素の順番が変わる点がreshape()と異なる
arr2x3_T = arr2x3.T
print(arr2x3.T)
arr2x3_transpose = arr2x3.transpose()

[[1 4]
 [2 5]
 [3 6]]


In [32]:
# 重要なところ
"""
・arrange(2, 11, 2)で得られる配列は？
    [2, 4, 6, 8, 10]
    
・arange()とlinspace()の違いは？
    arangeは終了の値を含まない
    linspaceは終了の値を含むように等間隔に数列を生成
    
・Numpy配列の形状（行・列）を変更したいときに使う関数は？
    reshape()
    trasepose()
"""

'\n・arrange(2, 11, 2)で得られる配列は？\n    [2, 4, 6, 8, 10]\n    \n・arange()とlinspace()の違いは？\n    arangeは終了の値を含まない\n    linspaceは終了の値を含むように等間隔に数列を生成\n    \n・Numpy配列の形状（行・列）を変更したいときに使う関数は？\n    reshape()\n    trasepose()\n'

In [77]:
"""
演習問題
１．0から14の連番が入った配列aを作成せよ
２．配列aを3行5列に整列した配列bを作成せよ
３．配列aとbの形状（行と列の数）を確認せよ
"""

a = np.arange(15)
print(f"1: a = {a}")

b = a.reshape(3, 5)
print(f"2: b = {b}")

print("3: ", end = "")
print(a.shape)
print(b.shape)

1: a = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
2: b = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
3: (15,)
(3, 5)


In [48]:
# Numpy配列に対する数学的演算
# 足し算・引き算

a = np.array([0, 1, 2, 3, 9])
b = np.array([2, 4, 6, 0, np.inf])
print(f"a = {a}")
print(f"b = {b}")
print()

#足し算(+, np.add(a, b))
print(f"a + b = {a + b}")
print(f"a + 3 = {a + 3}")
print()

# 引き算(-, np.subtract(a, b))
print(f"a - b = {a - b}")
print(f"a - 3 = {a - 3}")

a = [0 1 2 3 9]
b = [ 2.  4.  6.  0. inf]

a + b = [ 2.  5.  8.  3. inf]
a + 3 = [ 3  4  5  6 12]

a - b = [ -2.  -3.  -4.   3. -inf]
a - 3 = [-3 -2 -1  0  6]


In [49]:
"""
足し算
a + b, np.add(a, b)

引き算
a - b, np.subtract(a, b)

掛け算
a * b, multiply(a, b)

割り算
a / b

商（割り算の商の整数部分）
a // b

割り算の余り
a % b

aのb乗
a ** b, np.power(a, b)

平方根
np.sqrt(a)

行列Aと行列Bの要素積(同じ位置の要素毎に掛け算)
A * B

行列Aと行列Bの積(線形代数の行列の掛け算)
np.dot(A, B)
"""

'\n足し算\na + b, np.add(a, b)\n\n引き算\na - b, np.subtract(a, b)\n\n掛け算\na * b, multiply(a, b)\n\n割り算\na / b\n\n商（割り算の商の整数部分）\na // b\n\n割り算の余り\na % b\n\naのb乗\na ** b, np.power(a, b)\n\n平方根\nnp.sqrt(a)\n\n行列Aと行列Bの要素積(同じ位置の要素毎に掛け算)\nA * B\n\n行列Aと行列Bの積(線形代数の行列の掛け算)\nnp.dot(A, B)\n'

In [76]:
# 行列積

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


# 同じ要素番号同士の掛け算、要素積
print("A * B = ")
print(A * B)
print()

# 行列の掛け算(np.dot(A, B)でも可)、行列積
print("A.dot(B) = ")
print(A.dot(B))
"""
行列のかけ算の計算方法：
・左は横でまとめる
・右は縦でまとめる
・まとめたもの同士かけ算（内積）
行列の積はAの列数とBの行数が一致していないとできない
"""

A * B = 
[[ 5 12]
 [21 32]]

A.dot(B) = 
[[19 22]
 [43 50]]


'\n行列のかけ算の計算方法：\n・左は横でまとめる\n・右は縦でまとめる\n・まとめたもの同士かけ算（内積）\n行列の積はAの列数とBの行数が一致していないとできない\n'

In [61]:
a = np.array([1, 2, 3, 4, 5])
print(f"総和： {sum(a)}")
print(f"最小値： {min(a)}")
print(f"最大値： {max(a)}")
print(f"平均値： {np.mean(a)}")
print(f"標準偏差： {np.std(a)}")

総和： 15
最小値： 1
最大値： 5
平均値： 3.0
標準偏差： 1.4142135623730951


In [71]:
# 軸の概念
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("a =")
print(a)
print()

# 要素の総和
print(f"要素の総和： a.sum() = {a.sum()}")

# 行方向の和(各行の同じ位置の要素毎の和)
print(f"行方向の和： a.sum(axis = 0) = {a.sum(axis = 0)}")

# 列方向の和(各列の同じ位置の要素の和)
print(f"列方向の和： a.sum(axis = 1) = {a.sum(axis = 1)}")

a =
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

要素の総和： a.sum() = 78
行方向の和： a.sum(axis = 0) = [15 18 21 24]
列方向の和： a.sum(axis = 1) = [10 26 42]


In [73]:
# その他の数学的処理
# 関数にはnp.をつけること

"""
三角関数
sin(), cos(), tan()

逆三角関数
arcsin(), arccos(), arctan()

指数関数
exp()

対数関数
log(), log10()

絶対値
abs()

(円周率)
np.pi
"""

'\n三角関数\nsin(), cos(), tan()\n\n逆三角関数\narcsin(), arccos(), arctan()\n\n指数関数\nexp()\n\n対数関数\nlog(), log10()\n\n絶対値\nabs()\n\n(円周率)\nnp.pi\n'

In [74]:
"""
重要なところの理解を確認

・aのb乗
    **
・行列の要素積
    *
・行列積
    dot()
・Numpyにおける「軸」とは？
    axis = 0は行方向、axis = 1は列方向
"""

'\n重要なところの理解を確認\n\n・aのb乗\n    **\n・行列の要素積\n    *\n・行列積\n    dot()\n・Numpyにおける「軸」とは？\n    axis = 0は行方向、axis = 1は列方向\n'

In [96]:
"""
演習問題
１．1から10までの連番が入った配列aを作成せよ
２．配列aを2行5列の2次元配列の形式に変換せよ
３．1から5までの連番が入った配列b0と、6から10までの連番が入った配列b1を作成し、
　　同じ位置の要素ごとの足し算、引き算、掛け算、割り算の結果を表示せよ
"""

a = np.arange(1, 11)
print("1: a =np.arange(1, 11) =")
print(a)
print()

b= a.reshape(2, 5)
print("2: b = a.reshape(2, 5) =")
print(b)
print()

b0 = b[0]
b1 = b[1]
wa = b0 + b1
sa = b0 - b1
seki = b0 * b1
sho = b0 / b1

print("3:")
print(f"b0 = b[0] = {b0}")
print(f"b1 = b[1] = {b1}")
print(f"wa = b0 + b1 = {b0 + b1}")
print(f"sa = b0 - b1 = {b0 - b1}")
print(f"seki = b0 * b1 = {b0 * b1}")
print(f"sho = b0 / b1 = {b0 / b1}")

1: a =np.arange(1, 11) =
[ 1  2  3  4  5  6  7  8  9 10]

2: b = a.reshape(2, 5) =
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

3:
b0 = b[0] = [1 2 3 4 5]
b1 = b[1] = [ 6  7  8  9 10]
wa = b0 + b1 = [ 7  9 11 13 15]
sa = b0 - b1 = [-5 -5 -5 -5 -5]
seki = b0 * b1 = [ 6 14 24 36 50]
sho = b0 / b1 = [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [97]:
"""内部データの参照"""

'内部データの参照'

In [100]:
# 内部データの参照
# スライス：リストやタプルなどの複数のデータに対して一部分のデータを取得する操作
# 先頭から数えるときは0, 1, 2,...末尾から数えるときは-1, -2, -3,...
a = np.array(["あ", "い", "う", "え", "お"])

print(f"{a[2]} = a[2], a[-3]")

う = a[2], a[-3]


In [122]:
# 内部データの参照
# 「一度に」複数取り出す場合は「引数をリスト」で指定する(a[0, 2]はaの0行目の2列目という意味になるから？)
# 1行のリストだからこのように書くのか？
# "あ"と"う"を取り出す場合(同じように書いてのPythonではできない)

print(a[[0, 2]])

['あ' 'う']


In [105]:
# 内部データの参照
# a[始 : 終]　終わりは含まれない、この場合は引数はリストにしない
print(a[1 : 4])
# a[始 : 終 : 間隔]も可能
print(a[0 : 4 : 2])

['い' 'う' 'え']
['あ' 'う']


In [108]:
# 二次元配列における参照
b = np.array([[1, 2, 3], [4, 5, 6]])

# 1行目の2列目
print(b[1, 2])

# 任意(すべて)の行の2列目
print(b[:, 2])

6
[3 6]


In [110]:
b[:, [0, 2]]
# 任意(すべて)の行の0列目と2列目

array([[1, 3],
       [4, 6]])

In [121]:
b = np.array([range(5), range(1, 6), range(2, 7), range(3, 8), range(4, 9)])
print(b)
print()

print(b[-1])
print()

print(b[range(5),range(5)])
# b[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
# = b[0, 0], b[1, 1], b[2, 2], b[3, 3], b[4, 4]

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]

[4 5 6 7 8]

[0 2 4 6 8]


In [127]:
# 条件に合った要素の抜き出し
# np.where(条件式, 真の場合の値, 偽の場合の値)
a = np.arange(20).reshape((4,5))
print(a)
print()

# aの要素が3の倍数であれば1、そうでなければ0をかえす
b = np.where((a > 0) & (a % 3 == 0), 1, 0)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[0 0 0 1 0]
 [0 1 0 0 1]
 [0 0 1 0 0]
 [1 0 0 1 0]]


In [131]:
"""
知識の確認
"""
a = np.array(["あ", "い", "う", "え", "お"])
b = np.array(range(1, 7)).reshape(2, 3)
print(a)
print(b)
print()

# aから"い"を取り出す
print(a[1])
print()

# bから3列目を取り出す
print(b[:, 2])

['あ' 'い' 'う' 'え' 'お']
[[1 2 3]
 [4 5 6]]

い

[3 6]


In [7]:
"""演習問題"""
# 問題１
# 順番に１～２５が入る5×5の配列を定義し、標準出力せよ
a = np.arange(1, 26).reshape(5, 5)
print(a)
print()

# 問題2
# 行列の特定範囲を抽出
# 7,8,12,13がある範囲を標準出力せよ(赤枠で囲まれていた)
print(a[1: 3, 1: 3])
# 1行目から2行目の1列目から2列目

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[ 7  8]
 [12 13]]
